### PR TITLE
Remove Dock from core component, convert layout to flexbox for better usage elsewhere

### PR DESCRIPTION
**Pull request by abettadapur**
- Absolute positioning caused problems rendering this component outside of the Dock component
- Moved the dock portion of the component to a separate component so it can be used independently

### CODE REVIEW

**Comment by abettadapur** [comment]
@yelouafi Could you take a look?
In addition, I am happy to take over maintenance of this repository if you no longer have the time

**Comment by abettadapur** [comment]
@yelouafi Could you take a look?
In addition, I am happy to take over maintenance of this repository if you no longer have the time

**Comment by mshustov** [comment]
@Andarist probably you can help here?

**Comment by Andarist** [comment]
@abettadapur I've made u a collaborator, feel free to merge any changes you see appropriate - if u want u can also move your extension to the redux-saga organization or just import it here and make this a monorepo (might ease development)

**Pull request merged**
